# Generated by Django 4.2.2 on 2023-10-04 16:17

import clubform.models
from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, validators=[clubform.models.Form.validate_name])),
                ('surname', models.CharField(max_length=30, validators=[clubform.models.Form.validate_surname])),
                ('age', models.IntegerField(validators=[clubform.models.Form.validate_age])),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female'), ('o', 'other'), ('nd', 'non defined'), ('ah', 'apache helicopter')], max_length=100)),
                ('email', models.EmailField(max_length=254, validators=[clubform.models.Form.ValidateEmail])),
                ('schedule_time', models.TimeField()),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('username', models.CharField(max_length=100, validators=[clubform.models.Form.NoDigitsValidator])),
                ('favourite_game', models.CharField(max_length=100)),
                ('place_of_notice', models.CharField(choices=[('YOUTUBE', 'Youtube'), ('INSTAGRAM', 'Instagram'), ('FRIENDS', 'Friends'), ('X', 'X')], max_length=60)),
            ],
        ),
    ]
